print("Nombre del alumno: Melany Marlen Chavez Ortiz")
print("Lugar de recidencia: Aguascalientes")
print("Fecha de nacimiento: 15 de Febrero del 2003")
print("Color favorito: Rosa y Morado")
print ("Animal favorito: Gato y Tigre")

print("1.-¿Que es la programacion?")
print("La programacion es un proceso donde se usan maquinas para ejecutar un programa que se tiene en mente.")
print("2.- ¿Porque es importante la programacion?")
print("Es muy importante debido a que causa el imacto tan avanzado que tenemos en la actualidad, debido a ella, tenemos varios conocimientos sobre la computacion y ejecucion de aplicaciones en software")
print("3.- Explique con sus palabras que es herencia:")
print("La herencia para mi es cuando una clase puede heredar atributos a objetos aunque no sean de la misma clase")
print("4.- Explique con sus palabras que es el polimorfismo:")
print("Es cuando una palabra tiene diferente significado en una accion, un ejemplo es la palabra abrir con diferente funcion a una puerta o caja")
print("5.- Explique con sus propias palabras que es abstraccion:")
print("Significa el utilizar menos datos a la hora de realizar una accion que no necesita de todos estos en un grupo.")
print("6.- Explique con sus palabras que es encapsulamiento:")
print("Es ocultamiento de informacion, cuando se puede mostrar una imagen al publico sin necesidad de mostrar todo su proceso")